const mysql = require('mysql2/promise')

async function insertFackerRoom() {
  const connection = await mysql.createConnection({
    host: 'localhost',
    user: 'root',
    password: '',
    database: 'hospital'
  })

  const rooms = [
    ['Chambre 1', 'VIP', 1, 'Bâtiment 1', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 2', 'VIP', 1, 'Bâtiment 1', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 3', 'soins intensifs', 1, 'Bâtiment 1', 'disponible', 'Isolation sonore'],
    ['Chambre 4', 'VIP', 1, 'Bâtiment 1', 'disponible', 'Isolation sonore'],
    ['Chambre 5', 'standard', 1, 'Bâtiment 1', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 6', 'VIP', 1, 'Bâtiment 1', 'disponible', 'Climatisation, Salle de bain privée'],
    ['Chambre 7', 'soins intensifs', 1, 'Bâtiment 1', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 8', 'double', 1, 'Bâtiment 1', 'maintenance', 'TV, Wi-Fi'],
    ['Chambre 9', 'standard', 1, 'Bâtiment 1', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 10', 'double', 1, 'Bâtiment 1', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 1', 'VIP', 2, 'Bâtiment 1', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 2', 'VIP', 2, 'Bâtiment 1', 'disponible', 'Isolation sonore'],
    ['Chambre 3', 'double', 2, 'Bâtiment 1', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 4', 'soins intensifs', 2, 'Bâtiment 1', 'disponible', 'Isolation sonore'],
    ['Chambre 5', 'VIP', 2, 'Bâtiment 1', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 6', 'double', 2, 'Bâtiment 1', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 7', 'standard', 2, 'Bâtiment 1', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 8', 'isolement', 2, 'Bâtiment 1', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 9', 'standard', 2, 'Bâtiment 1', 'disponible', 'Climatisation, Salle de bain privée'],
    [
      'Chambre 10',
      'isolement',
      2,
      'Bâtiment 1',
      'disponible',
      'Climatisation, Salle de bain privée'
    ],
    ['Chambre 1', 'double', 3, 'Bâtiment 1', 'disponible', 'Isolation sonore'],
    ['Chambre 2', 'standard', 3, 'Bâtiment 1', 'disponible', 'TV, Wi-Fi'],
    [
      'Chambre 3',
      'soins intensifs',
      3,
      'Bâtiment 1',
      'disponible',
      'Climatisation, Salle de bain privée'
    ],
    [
      'Chambre 4',
      'isolement',
      3,
      'Bâtiment 1',
      'disponible',
      'Climatisation, Salle de bain privée'
    ],
    ['Chambre 5', 'double', 3, 'Bâtiment 1', 'disponible', 'Isolation sonore'],
    ['Chambre 6', 'VIP', 3, 'Bâtiment 1', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 7', 'isolement', 3, 'Bâtiment 1', 'disponible', 'Lit médicalisé, Oxygène'],
    [
      'Chambre 8',
      'isolement',
      3,
      'Bâtiment 1',
      'disponible',
      'Climatisation, Salle de bain privée'
    ],
    ['Chambre 9', 'standard', 3, 'Bâtiment 1', 'disponible', 'Isolation sonore'],
    ['Chambre 10', 'isolement', 3, 'Bâtiment 1', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 1', 'isolement', 4, 'Bâtiment 1', 'disponible', 'Isolation sonore'],
    ['Chambre 2', 'soins intensifs', 4, 'Bâtiment 1', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 3', 'double', 4, 'Bâtiment 1', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 4', 'VIP', 4, 'Bâtiment 1', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 5', 'soins intensifs', 4, 'Bâtiment 1', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 6', 'standard', 4, 'Bâtiment 1', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 7', 'double', 4, 'Bâtiment 1', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 8', 'soins intensifs', 4, 'Bâtiment 1', 'disponible', 'Isolation sonore'],
    ['Chambre 9', 'isolement', 4, 'Bâtiment 1', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 10', 'isolement', 4, 'Bâtiment 1', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 1', 'soins intensifs', 1, 'Bâtiment 2', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 2', 'double', 1, 'Bâtiment 2', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 3', 'double', 1, 'Bâtiment 2', 'disponible', 'Isolation sonore'],
    ['Chambre 4', 'VIP', 1, 'Bâtiment 2', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 5', 'soins intensifs', 1, 'Bâtiment 2', 'disponible', 'Isolation sonore'],
    ['Chambre 6', 'VIP', 1, 'Bâtiment 2', 'disponible', 'Isolation sonore'],
    ['Chambre 7', 'VIP', 1, 'Bâtiment 2', 'disponible', 'Isolation sonore'],
    ['Chambre 8', 'soins intensifs', 1, 'Bâtiment 2', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 9', 'isolement', 1, 'Bâtiment 2', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 10', 'double', 1, 'Bâtiment 2', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 1', 'VIP', 2, 'Bâtiment 2', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 2', 'isolement', 2, 'Bâtiment 2', 'disponible', 'Isolation sonore'],
    ['Chambre 3', 'soins intensifs', 2, 'Bâtiment 2', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 4', 'isolement', 2, 'Bâtiment 2', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 5', 'standard', 2, 'Bâtiment 2', 'disponible', 'Isolation sonore'],
    ['Chambre 6', 'double', 2, 'Bâtiment 2', 'disponible', 'Accès handicapé, Interphone'],
    [
      'Chambre 7',
      'isolement',
      2,
      'Bâtiment 2',
      'disponible',
      'Climatisation, Salle de bain privée'
    ],
    ['Chambre 8', 'double', 2, 'Bâtiment 2', 'disponible', 'Isolation sonore'],
    ['Chambre 9', 'soins intensifs', 2, 'Bâtiment 2', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 10', 'isolement', 2, 'Bâtiment 2', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 1', 'isolement', 3, 'Bâtiment 2', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 2', 'soins intensifs', 3, 'Bâtiment 2', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 3', 'isolement', 3, 'Bâtiment 2', 'disponible', 'Isolation sonore'],
    ['Chambre 4', 'isolement', 3, 'Bâtiment 2', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 5', 'VIP', 3, 'Bâtiment 2', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 6', 'soins intensifs', 3, 'Bâtiment 2', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 7', 'standard', 3, 'Bâtiment 2', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 8', 'double', 3, 'Bâtiment 2', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 9', 'double', 3, 'Bâtiment 2', 'disponible', 'Isolation sonore'],
    ['Chambre 10', 'isolement', 3, 'Bâtiment 2', 'disponible', 'Lit médicalisé, Oxygène'],
    [
      'Chambre 1',
      'soins intensifs',
      4,
      'Bâtiment 2',
      'disponible',
      'Climatisation, Salle de bain privée'
    ],
    ['Chambre 2', 'VIP', 4, 'Bâtiment 2', 'disponible', 'Isolation sonore'],
    ['Chambre 3', 'soins intensifs', 4, 'Bâtiment 2', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 4', 'double', 4, 'Bâtiment 2', 'disponible', 'Isolation sonore'],
    ['Chambre 5', 'double', 4, 'Bâtiment 2', 'disponible', 'Climatisation, Salle de bain privée'],
    ['Chambre 6', 'isolement', 4, 'Bâtiment 2', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 7', 'VIP', 4, 'Bâtiment 2', 'disponible', 'Isolation sonore'],
    ['Chambre 8', 'soins intensifs', 4, 'Bâtiment 2', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 9', 'soins intensifs', 4, 'Bâtiment 2', 'disponible', 'Isolation sonore'],
    ['Chambre 10', 'VIP', 4, 'Bâtiment 2', 'disponible', 'Climatisation, Salle de bain privée'],
    ['Chambre 1', 'double', 1, 'Bâtiment 3', 'disponible', 'TV, Wi-Fi'],
    [
      'Chambre 2',
      'soins intensifs',
      1,
      'Bâtiment 3',
      'disponible',
      'Climatisation, Salle de bain privée'
    ],
    ['Chambre 3', 'double', 1, 'Bâtiment 3', 'maintenance', 'Isolation sonore'],
    ['Chambre 4', 'VIP', 1, 'Bâtiment 3', 'disponible', 'Isolation sonore'],
    [
      'Chambre 5',
      'soins intensifs',
      1,
      'Bâtiment 3',
      'disponible',
      'Climatisation, Salle de bain privée'
    ],
    ['Chambre 6', 'VIP', 1, 'Bâtiment 3', 'disponible', 'Climatisation, Salle de bain privée'],
    ['Chambre 7', 'isolement', 1, 'Bâtiment 3', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 8', 'soins intensifs', 1, 'Bâtiment 3', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 9', 'standard', 1, 'Bâtiment 3', 'disponible', 'Climatisation, Salle de bain privée'],
    ['Chambre 10', 'VIP', 1, 'Bâtiment 3', 'disponible', 'Climatisation, Salle de bain privée'],
    ['Chambre 1', 'standard', 2, 'Bâtiment 3', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 2', 'VIP', 2, 'Bâtiment 3', 'disponible', 'Isolation sonore'],
    ['Chambre 3', 'standard', 2, 'Bâtiment 3', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 4', 'double', 2, 'Bâtiment 3', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 5', 'standard', 2, 'Bâtiment 3', 'disponible', 'Climatisation, Salle de bain privée'],
    ['Chambre 6', 'VIP', 2, 'Bâtiment 3', 'disponible', 'Climatisation, Salle de bain privée'],
    ['Chambre 7', 'standard', 2, 'Bâtiment 3', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 8', 'isolement', 2, 'Bâtiment 3', 'disponible', 'Lit médicalisé, Oxygène'],
    [
      'Chambre 9',
      'isolement',
      2,
      'Bâtiment 3',
      'maintenance',
      'Climatisation, Salle de bain privée'
    ],
    [
      'Chambre 10',
      'isolement',
      2,
      'Bâtiment 3',
      'disponible',
      'Climatisation, Salle de bain privée'
    ],
    ['Chambre 1', 'VIP', 3, 'Bâtiment 3', 'disponible', 'Isolation sonore'],
    ['Chambre 2', 'double', 3, 'Bâtiment 3', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 3', 'double', 3, 'Bâtiment 3', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 4', 'VIP', 3, 'Bâtiment 3', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 5', 'double', 3, 'Bâtiment 3', 'disponible', 'Lit médicalisé, Oxygène'],
    [
      'Chambre 6',
      'soins intensifs',
      3,
      'Bâtiment 3',
      'disponible',
      'Climatisation, Salle de bain privée'
    ],
    ['Chambre 7', 'soins intensifs', 3, 'Bâtiment 3', 'disponible', 'Isolation sonore'],
    ['Chambre 8', 'VIP', 3, 'Bâtiment 3', 'disponible', 'Climatisation, Salle de bain privée'],
    ['Chambre 9', 'soins intensifs', 3, 'Bâtiment 3', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 10', 'standard', 3, 'Bâtiment 3', 'disponible', 'Isolation sonore'],
    ['Chambre 1', 'standard', 4, 'Bâtiment 3', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 2', 'standard', 4, 'Bâtiment 3', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 3', 'isolement', 4, 'Bâtiment 3', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 4', 'standard', 4, 'Bâtiment 3', 'disponible', 'Isolation sonore'],
    ['Chambre 5', 'soins intensifs', 4, 'Bâtiment 3', 'disponible', 'TV, Wi-Fi'],
    [
      'Chambre 6',
      'isolement',
      4,
      'Bâtiment 3',
      'disponible',
      'Climatisation, Salle de bain privée'
    ],
    ['Chambre 7', 'soins intensifs', 4, 'Bâtiment 3', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 8', 'isolement', 4, 'Bâtiment 3', 'disponible', 'Isolation sonore'],
    ['Chambre 9', 'soins intensifs', 4, 'Bâtiment 3', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 10', 'standard', 4, 'Bâtiment 3', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 1', 'double', 1, 'Bâtiment 4', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 2', 'standard', 1, 'Bâtiment 4', 'disponible', 'Accès handicapé, Interphone'],
    [
      'Chambre 3',
      'soins intensifs',
      1,
      'Bâtiment 4',
      'maintenance',
      'Climatisation, Salle de bain privée'
    ],
    ['Chambre 4', 'double', 1, 'Bâtiment 4', 'disponible', 'Isolation sonore'],
    ['Chambre 5', 'soins intensifs', 1, 'Bâtiment 4', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 6', 'soins intensifs', 1, 'Bâtiment 4', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 7', 'isolement', 1, 'Bâtiment 4', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 8', 'isolement', 1, 'Bâtiment 4', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 9', 'standard', 1, 'Bâtiment 4', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 10', 'double', 1, 'Bâtiment 4', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 1', 'VIP', 2, 'Bâtiment 4', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 2', 'VIP', 2, 'Bâtiment 4', 'disponible', 'Isolation sonore'],
    [
      'Chambre 3',
      'soins intensifs',
      2,
      'Bâtiment 4',
      'disponible',
      'Climatisation, Salle de bain privée'
    ],
    ['Chambre 4', 'double', 2, 'Bâtiment 4', 'disponible', 'Climatisation, Salle de bain privée'],
    ['Chambre 5', 'isolement', 2, 'Bâtiment 4', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 6', 'double', 2, 'Bâtiment 4', 'disponible', 'Isolation sonore'],
    ['Chambre 7', 'soins intensifs', 2, 'Bâtiment 4', 'disponible', 'TV, Wi-Fi'],
    [
      'Chambre 8',
      'isolement',
      2,
      'Bâtiment 4',
      'disponible',
      'Climatisation, Salle de bain privée'
    ],
    [
      'Chambre 9',
      'isolement',
      2,
      'Bâtiment 4',
      'disponible',
      'Climatisation, Salle de bain privée'
    ],
    [
      'Chambre 10',
      'soins intensifs',
      2,
      'Bâtiment 4',
      'disponible',
      'Climatisation, Salle de bain privée'
    ],
    ['Chambre 1', 'double', 3, 'Bâtiment 4', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 2', 'VIP', 3, 'Bâtiment 4', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 3', 'standard', 3, 'Bâtiment 4', 'disponible', 'TV, Wi-Fi'],
    [
      'Chambre 4',
      'soins intensifs',
      3,
      'Bâtiment 4',
      'disponible',
      'Climatisation, Salle de bain privée'
    ],
    ['Chambre 5', 'VIP', 3, 'Bâtiment 4', 'disponible', 'Isolation sonore'],
    ['Chambre 6', 'isolement', 3, 'Bâtiment 4', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 7', 'VIP', 3, 'Bâtiment 4', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 8', 'double', 3, 'Bâtiment 4', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 9', 'isolement', 3, 'Bâtiment 4', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 10', 'isolement', 3, 'Bâtiment 4', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 1', 'VIP', 4, 'Bâtiment 4', 'disponible', 'Climatisation, Salle de bain privée'],
    ['Chambre 2', 'isolement', 4, 'Bâtiment 4', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 3', 'soins intensifs', 4, 'Bâtiment 4', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 4', 'VIP', 4, 'Bâtiment 4', 'maintenance', 'Accès handicapé, Interphone'],
    ['Chambre 5', 'VIP', 4, 'Bâtiment 4', 'disponible', 'Isolation sonore'],
    ['Chambre 6', 'isolement', 4, 'Bâtiment 4', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 7', 'double', 4, 'Bâtiment 4', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 8', 'isolement', 4, 'Bâtiment 4', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 9', 'VIP', 4, 'Bâtiment 4', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 10', 'standard', 4, 'Bâtiment 4', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 1', 'double', 1, 'Bâtiment 5', 'disponible', 'Climatisation, Salle de bain privée'],
    ['Chambre 2', 'double', 1, 'Bâtiment 5', 'disponible', 'Climatisation, Salle de bain privée'],
    ['Chambre 3', 'standard', 1, 'Bâtiment 5', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 4', 'double', 1, 'Bâtiment 5', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 5', 'VIP', 1, 'Bâtiment 5', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 6', 'double', 1, 'Bâtiment 5', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 7', 'soins intensifs', 1, 'Bâtiment 5', 'disponible', 'Isolation sonore'],
    ['Chambre 8', 'isolement', 1, 'Bâtiment 5', 'disponible', 'Isolation sonore'],
    ['Chambre 9', 'standard', 1, 'Bâtiment 5', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 10', 'VIP', 1, 'Bâtiment 5', 'disponible', 'Accès handicapé, Interphone'],
    [
      'Chambre 1',
      'soins intensifs',
      2,
      'Bâtiment 5',
      'disponible',
      'Climatisation, Salle de bain privée'
    ],
    ['Chambre 2', 'isolement', 2, 'Bâtiment 5', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 3', 'soins intensifs', 2, 'Bâtiment 5', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 4', 'standard', 2, 'Bâtiment 5', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 5', 'VIP', 2, 'Bâtiment 5', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 6', 'standard', 2, 'Bâtiment 5', 'disponible', 'Isolation sonore'],
    ['Chambre 7', 'isolement', 2, 'Bâtiment 5', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 8', 'VIP', 2, 'Bâtiment 5', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 9', 'VIP', 2, 'Bâtiment 5', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 10', 'isolement', 2, 'Bâtiment 5', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 1', 'double', 3, 'Bâtiment 5', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 2', 'double', 3, 'Bâtiment 5', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 3', 'soins intensifs', 3, 'Bâtiment 5', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 4', 'standard', 3, 'Bâtiment 5', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 5', 'standard', 3, 'Bâtiment 5', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 6', 'double', 3, 'Bâtiment 5', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 7', 'VIP', 3, 'Bâtiment 5', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 8', 'isolement', 3, 'Bâtiment 5', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 9', 'VIP', 3, 'Bâtiment 5', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 10', 'standard', 3, 'Bâtiment 5', 'disponible', 'Accès handicapé, Interphone'],
    ['Chambre 1', 'soins intensifs', 4, 'Bâtiment 5', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 2', 'soins intensifs', 4, 'Bâtiment 5', 'disponible', 'Isolation sonore'],
    ['Chambre 3', 'isolement', 4, 'Bâtiment 5', 'disponible', 'Lit médicalisé, Oxygène'],
    ['Chambre 4', 'standard', 4, 'Bâtiment 5', 'disponible', 'Climatisation, Salle de bain privée'],
    ['Chambre 5', 'soins intensifs', 4, 'Bâtiment 5', 'disponible', 'TV, Wi-Fi'],
    ['Chambre 6', 'double', 4, 'Bâtiment 5', 'disponible', 'Accès handicapé, Interphone'],
    [
      'Chambre 7',
      'isolement',
      4,
      'Bâtiment 5',
      'disponible',
      'Climatisation, Salle de bain privée'
    ],
    ['Chambre 8', 'VIP', 4, 'Bâtiment 5', 'disponible', 'Accès handicapé, Interphone'],
    [
      'Chambre 9',
      'soins intensifs',
      4,
      'Bâtiment 5',
      'disponible',
      'Climatisation, Salle de bain privée'
    ],
    ['Chambre 10', 'isolement', 4, 'Bâtiment 5', 'disponible', 'Isolation sonore']
  ]

  try {
    for (const room of rooms) {
      await connection.execute(
        'INSERT INTO rooms (name, type, floor, building, status, features) VALUES (?, ?, ?, ?, ?, ?)',
        room
      )
    }

    console.log('✅ Insertion des rooms réussie.')
  } catch (error) {
    console.error('❌ Error inserting rooms:', error)
    console.error('Vous avez peut-être déjà inséré ces données.')
  } finally {
    await connection.end()
  }
}

module.exports = { insertFackerRoom }
